
interface SlideData {
    title: string;
    subTitle?: string;
    points: string[];
    tableData?: string[][];
    nextSteps?: string[];
}

export const generateVbaScript = (slides: SlideData[]): string => {
    if (slides.length === 0) return "";

    let script = `Sub SciFlowPro_AutoPPT_Modular()
    ' Generated by SciFlow Pro - Multi-Slide Visual Template
    Dim pptApp As Object
    Dim pptPres As Object
    Dim pptSlide As Object
    Dim pptShape As Object
    Dim pptTable As Object
    Dim i As Integer, r As Integer, c As Integer
    Dim bodyTop As Single
    Dim bodyHeight As Single
    
    ' 1. Initialize PowerPoint Application
    On Error Resume Next
    Set pptApp = GetObject(, "PowerPoint.Application")
    If Err.Number <> 0 Then
        Set pptApp = CreateObject("PowerPoint.Application")
    End If
    On Error GoTo 0
    
    pptApp.Visible = True
    Set pptPres = pptApp.Presentations.Add
    
`;

    slides.forEach((s, idx) => {
        const slideIndex = idx + 1;
        script += `
    ' --- Slide ${slideIndex}: ${s.title} ---
    Set pptSlide = pptPres.Slides.Add(${slideIndex}, 12)
    
    ' Header
    Set pptShape = pptSlide.Shapes.AddShape(1, 0, 0, 960, 80) ' msoShapeRectangle
    pptShape.Fill.ForeColor.RGB = RGB(30, 27, 75)
    pptShape.Line.Visible = 0
    
    ' Title
    Set pptShape = pptSlide.Shapes.AddTextbox(1, 40, 20, 800, 50)
    With pptShape.TextFrame.TextRange
        .Text = "${s.title.replace(/"/g, '""')}"
        .Font.Name = "Calibri"
        .Font.Size = 24
        .Font.Bold = -1
        .Font.Color.RGB = RGB(255, 255, 255)
    End With
    
    bodyTop = 100
    bodyHeight = 420
`;

        if (s.subTitle) {
            script += `
    Set pptShape = pptSlide.Shapes.AddTextbox(1, 50, bodyTop, 860, 30)
    With pptShape.TextFrame.TextRange
        .Text = "${s.subTitle.replace(/"/g, '""')}"
        .Font.Name = "Calibri"
        .Font.Size = 14
        .Font.Bold = -1
        .Font.Color.RGB = RGB(79, 70, 229)
    End With
    bodyTop = bodyTop + 36
    bodyHeight = bodyHeight - 36
`;
        }

        if (s.tableData && s.tableData.length > 0 && s.tableData[0]?.length > 0) {
            const rows = s.tableData.length;
            const cols = s.tableData[0].length;
            const tableHeight = Math.max(120, Math.min(280, rows * 30));
            script += `
    ' Table block
    Set pptShape = pptSlide.Shapes.AddTable(${rows}, ${cols}, 50, bodyTop, 860, ${tableHeight})
    Set pptTable = pptShape.Table
    With pptTable
`;
            s.tableData.forEach((row, rIdx) => {
                row.forEach((cell, cIdx) => {
                    const safeCell = cell.replace(/"/g, '""');
                    script += `        .Cell(${rIdx + 1}, ${cIdx + 1}).Shape.TextFrame.TextRange.Text = "${safeCell}"
        .Cell(${rIdx + 1}, ${cIdx + 1}).Shape.TextFrame.TextRange.Font.Name = "Calibri"
        .Cell(${rIdx + 1}, ${cIdx + 1}).Shape.TextFrame.TextRange.Font.Size = 11
        .Cell(${rIdx + 1}, ${cIdx + 1}).Shape.TextFrame.VerticalAnchor = 3
`;
                    if (rIdx === 0) {
                        script += `        .Cell(${rIdx + 1}, ${cIdx + 1}).Shape.Fill.ForeColor.RGB = RGB(79, 70, 229)
        .Cell(${rIdx + 1}, ${cIdx + 1}).Shape.TextFrame.TextRange.Font.Bold = -1
        .Cell(${rIdx + 1}, ${cIdx + 1}).Shape.TextFrame.TextRange.Font.Color.RGB = RGB(255, 255, 255)
`;
                    } else if (rIdx % 2 === 0) {
                        script += `        .Cell(${rIdx + 1}, ${cIdx + 1}).Shape.Fill.ForeColor.RGB = RGB(246, 248, 255)
`;
                    } else {
                        script += `        .Cell(${rIdx + 1}, ${cIdx + 1}).Shape.Fill.ForeColor.RGB = RGB(255, 255, 255)
`;
                    }
                });
            });
            script += `    End With
    bodyTop = bodyTop + ${tableHeight} + 20
`;
        }

        if (s.points && s.points.length > 0) {
            const pointsText = s.points.map(p => `• ${p.replace(/"/g, '""')}`).join('" & vbCrLf & "');
            script += `
    ' Bullet points
    Set pptShape = pptSlide.Shapes.AddTextbox(1, 50, bodyTop, 860, 220)
    With pptShape.TextFrame.TextRange
        .Text = "${pointsText}"
        .Font.Name = "Calibri"
        .Font.Size = 16
        .Font.Color.RGB = RGB(30, 41, 59)
        .ParagraphFormat.SpaceAfter = 10
    End With
`;
        }

        if (s.nextSteps && s.nextSteps.length > 0) {
            const nextText = s.nextSteps.map(step => step.replace(/"/g, '""')).join('  |  ');
            script += `
    ' Next steps footer
    Set pptShape = pptSlide.Shapes.AddShape(1, 50, 520, 860, 34)
    pptShape.Fill.ForeColor.RGB = RGB(238, 242, 255)
    pptShape.Line.ForeColor.RGB = RGB(165, 180, 252)
    pptShape.TextFrame.TextRange.Text = "NEXT STEPS: ${nextText}"
    pptShape.TextFrame.TextRange.Font.Name = "Calibri"
    pptShape.TextFrame.TextRange.Font.Size = 11
    pptShape.TextFrame.TextRange.Font.Bold = -1
    pptShape.TextFrame.TextRange.Font.Color.RGB = RGB(55, 48, 163)
`;
        }

        script += `
    ' Page number
    Set pptShape = pptSlide.Shapes.AddTextbox(1, 900, 540, 40, 20)
    pptShape.TextFrame.TextRange.Text = "${slideIndex}"
    pptShape.TextFrame.TextRange.Font.Size = 10
    pptShape.TextFrame.TextRange.Font.Color.RGB = RGB(148, 163, 184)
`;
    });

    script += `
    MsgBox "SciFlow Presentation Generated Successfully!", vbInformation
End Sub`;

    return script;
};
