
import saveAs from 'file-saver';

/**
 * 清洗文本以适配 Word 纯文本/HTML 导出
 */
export const cleanTextForWord = (text: string, context?: { pH: number, potential: number }): string => {
  if (!text) return "";
  let clean = text;
  // 统一替换动力学参数
  clean = clean.replace(/\$?\s*j_0\s*\$?/g, 'j0').replace(/\$?\s*\\alpha\s*\$?/g, 'alpha').replace(/\$?\s*b_T\s*\$?/g, 'bT');
  // 替换特定的化学描述符
  clean = clean.replace(/\$?\s*OH\s*\^\s*\*\s*\$?/g, '羟基中间体吸附态');
  // 为化学式下标提供标准 HTML 渲染支持
  clean = clean.replace(/([A-Z][a-z]?)(\d+)/g, (match, element, num) => `${element}<sub>${num}</sub>`);
  // 清理剩余的 LaTeX 和 Markdown 符号
  clean = clean.replace(/\$\$(.*?)\$\$/g, '$1').replace(/\$(.*?)\$/g, '$1').replace(/\\/g, '').replace(/\$/g, '');
  return clean.trim();
};

/**
 * 导出为带有专业格式和页眉的 Word 文档
 */
export const exportToWord = (title: string, contentHTML: string, context?: { pH: number, potential: number }) => {
  const cleanTitle = cleanTextForWord(title);
  let processedContent = contentHTML;
  
  if (!contentHTML.includes('<h1') && !contentHTML.includes('<div')) {
      processedContent = cleanTextForWord(contentHTML, context)
        .replace(/^# (.*$)/gim, '<h1>$1</h1>')
        .replace(/^## (.*$)/gim, '<h2>$1</h2>')
        .replace(/\*\*(.*?)\*\*/g, '<b>$1</b>')
        .replace(/\n/g, '<br/>');
  }

  // 特殊处理：如果包含 references-container，为其每一行添加 Word 悬挂缩进属性
  if (processedContent.includes('references-container')) {
      processedContent = processedContent.replace(/class="ref-line"/g, 'class="reference-item" style="mso-special-format:bullet; text-indent:-21.0pt; margin-left:21.0pt;"');
  }

  const header = `
    <html xmlns:o='urn:schemas-microsoft-com:office:office' 
          xmlns:w='urn:schemas-microsoft-com:office:word' 
          xmlns='http://www.w3.org/TR/REC-html40'>
    <head>
      <meta charset='utf-8'>
      <style>
        @page { size: A4; margin: 2.54cm; }
        body { font-family: 'Times New Roman', 'SimSun', serif; font-size: 12pt; line-height: 1.8; text-align: justify; }
        h1 { font-size: 22pt; font-weight: bold; text-align: center; margin-bottom: 30px; }
        h2 { font-size: 16pt; font-weight: bold; margin-top: 24px; color: #2E56A5; border-bottom: 1px solid #EEE; }
        p { margin-bottom: 12px; text-indent: 2em; }
        .reference-item { 
            text-indent: -21.0pt; 
            margin-left: 21.0pt; 
            margin-bottom: 6pt; 
            line-height: 1.5;
            font-size: 10.5pt;
        }
        table { border-collapse: collapse; width: 100%; border: 1.5pt solid #000; }
        th, td { border: 0.5pt solid #000; padding: 10px; }
        .footer { text-align: center; margin-top: 40px; font-size: 9pt; color: #999; border-top: 1px solid #eee; padding-top: 20px; }
      </style>
    </head>
    <body>
      <div style="font-size:9pt; text-align:right; border-bottom:1px dashed #ccc;">SciFlow 数字化科研归档 | 生成时间：${new Date().toLocaleString()}</div>
      <h1>${cleanTitle}</h1>
  `;

  const footer = `<div class="footer">Generated by SciFlow Intelligent Research Engine</div></body></html>`;
  const sourceHTML = header + processedContent + footer;
  const blob = new Blob(['\ufeff', sourceHTML], { type: 'application/msword' });
  saveAs(blob, `${cleanTitle.replace(/\s+/g, '_')}_Report.doc`);
};
